### ISSUE TITLE
关于开发机上的热更问题

### ISSUE THREAD

**Issue by Kelier** [homkai/ehu#4]
这是一个很好的工具，但是我在使用上遇到了一些问题。譬如说启动ehu服务后，我修改文件虽然能检测到变化，但是页面上并没有进行刷新。

[多嘴一句，这个如果是fis发布的话是不是就不兼容呢？]

**Comment by homkai** [comment]
> 我修改文件虽然能检测到变化，但是页面上并没有进行刷新

这个工具的原理是 把esl 或者 requirejs 之类的 loader中  存module factory的局部变量放到全局
然后 监测到改动后 删除相关的module，重新load

你可以 按照这个思路 看下源码 然后 改一下给你自己用

**Comment by Kelier** [comment]
好的谢谢，当初我看到后面说支持tpl什么的，还以为直接修改模板会生效

在 2018年3月3日，下午11:05，Homkai <notifications@github.com<mailto:notifications@github.com>> 写道：


我修改文件虽然能检测到变化，但是页面上并没有进行刷新

这个工具的原理是 把esl 或者 requirejs 之类的 loader中 存module factory的局部变量放到全局
然后 监测到改动后 删除相关的module，重新load

你可以 按照这个思路 看下源码 然后 改一下给你自己用
